apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "equipments-service.fullname" . }}
  labels:
    {{- include "equipments-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "equipments-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.endpoint }}
      interval: 10s