image:
  tag: 9.3.6-debian-11-r5
admin:
  password: admin
service:
  type: NodePort
persistence:
  enabled: false
metrics:
  enabled: true
dashboardsProvider:
  enabled: true
dashboardsConfigMaps:
  - configMapName: equipments-service-dashboard
    fileName: equipments-service-dashboard.json
datasources:
  secretName: grafana-datasource-secret
